services:
  pgdb:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: acatamento_pedidos
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - pgdb
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./doc/erd:/var/lib/pgadmin/storage/admin_admin.com
      - ./pgadminservers.json:/pgadmin4/servers.json

volumes:
  pgdata:
  pgadmin_data:
